### PR TITLE
Add CI to the project

### PR DESCRIPTION
**Pull request by numb95**
I find out that you run the update script to update README.md then push it back to the repository. I add the CI based on Travis-ci. 
For that, I add my own token (which is invalid right now. I revoke it :D) but I will show you how to add your own key. With this feature, with every PR or push the `README.md` will be automaticly update, so you don't need to do anything. 

- For that first log in to [Travis-ci](https://travis-ci.org).
- Then navigate to [this](https://github.com/settings/tokens) and generate a personal token for Travis. mark all the repo checkbox. then copy the hash string
- Install the Travis CLI tool using this: `$ sudo gem install Travis` (make sure you have already installed the gem.
- Log in to it using `$ travis login` . you can use your username/password or the generated key for that (e.g `travis login --github-token HASHSTING`)
- After that run this to generate a secret. `travis encrypt GH_TOKEN="HASHSTRING"`
- Replace the `secure: NEW HASHED STRING` with that i addedd to `.travis.cli` 
- Push it to the repo and navigate to Travis to see the job. that will works fine

### CODE REVIEW

**Comment by numb95** [comment]
oh. there's a conflict in README.md. ignore mine. that would be ok.

**Comment by ashkanRmk** [comment]
Hi, thanks for your PR, but I made CI for this repo with Github Actions...
It run script automatically after each commit on master.
Look at .github folder for implementation.

**Comment by ashkanRmk** [comment]
Thanks again for the time you spent. 💙

**Comment by numb95** [comment]
Oh that's great. I will close the PR

**Pull request closed without merging**
